---
uint8 OUTCOME_OK=0
uint8 OUTCOME_NOT_CONNECTED=1
uint8 OUTCOME_TIMEOUT=2
uint8 OUTCOME_DEVICE_REJECTED=3
uint8 OUTCOME_PROTOCOL_ERROR=4
uint8 OUTCOME_IO_ERROR=5

uint8 STAGE_NONE=0
uint8 STAGE_ENTER_CONFIG=1
uint8 STAGE_READ_MAXIMUM_DISTANCE_GATE=2
uint8 STAGE_READ_TARGET_DISAPPEARANCE_DELAY=3
uint8 STAGE_EXIT_CONFIG=4

bool success
uint16 maximum_distance_gate
uint16 target_disappearance_delay_seconds
uint8 outcome
uint8 stage
string detail
